[package]
name = "cairo-coverage"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
cairo-lang-sierra.workspace = true
cairo-lang-sierra-to-casm.workspace = true
clap.workspace = true
derived-deref.workspace = true
itertools.workspace = true
serde.workspace = true
serde_json.workspace = true
trace-data.workspace = true
regex.workspace = true

[dev-dependencies]
assert_fs.workspace = true
snapbox.workspace = true
indoc.workspace = true
