name: Check installation script

on:
  pull_request:
    paths:
      - scripts/install.sh
      - .github/workflows/installation_script_check.yml
  push:
    branches:
      - main
    paths:
      - scripts/install.sh
      - .github/workflows/installation_script_check.yml
  release:
    types:
      - published

jobs:
  verify-installation-script:
    name: Verify installation script
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

          - target: aarch64-apple-darwin
            os: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install and check
        shell: bash
        run: |
          bash ./scripts/install.sh

          source ~/.bashrc

          if ! command -v cairo-coverage &> /dev/null; then
            echo "cairo-coverage was not installed"
            exit 1
          fi
